server.port: 8083
spring:
  datasource:
    url: jdbc:p6spy:postgresql://localhost:5432/postgres  # PostgreSQL ?? ??? ?????? ??
    username: postgres                              # PostgreSQL ??? ??
    password: postgres                              # PostgreSQL ????
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver # org.postgresql.Driver             # PostgreSQL ???? ???
    hikari:
      maximum-pool-size: 10                             # HikariCP ??? ?? ?? ?? (?? ? ??)
      minimum-idle: 5                                    # ?? ?? ??? ??
      pool-name: HikariCP                                # ? ??
  jpa:
    hibernate:
      ddl-auto: update                                    # ?????? ?? ???? ??
    show-sql: false                                         # p6spy? ?? ??
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

